/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cit260.checkers.frames;

import Exception.IntelException;
import chkrs.Board;
import intel.Moves;
import java.util.logging.Level;
import java.util.logging.Logger;
import select.SelectGui;

/**
 *
 * @author bensmac
 */
public class BoardGui extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public BoardGui() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel33 = new javax.swing.JPanel();
        Board = new javax.swing.JPanel();
        b0 = new javax.swing.JButton();
        d0 = new javax.swing.JButton();
        f0 = new javax.swing.JButton();
        h0 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        g1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        d2 = new javax.swing.JButton();
        f2 = new javax.swing.JButton();
        h2 = new javax.swing.JButton();
        g3 = new javax.swing.JButton();
        e3 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        d4 = new javax.swing.JButton();
        f4 = new javax.swing.JButton();
        h4 = new javax.swing.JButton();
        g5 = new javax.swing.JButton();
        e5 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        d6 = new javax.swing.JButton();
        f6 = new javax.swing.JButton();
        h6 = new javax.swing.JButton();
        g7 = new javax.swing.JButton();
        e7 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        a7 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton34 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel33.setBackground(new java.awt.Color(51, 255, 204));

        Board.setBackground(new java.awt.Color(102, 102, 102));

        b0.setBackground(new java.awt.Color(255, 255, 255));
        b0.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        b0.setText("O");
        b0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        b0.setPreferredSize(new java.awt.Dimension(50, 50));
        b0.setSize(new java.awt.Dimension(50, 50));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        d0.setBackground(new java.awt.Color(255, 255, 255));
        d0.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        d0.setText("O");
        d0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        d0.setPreferredSize(new java.awt.Dimension(50, 50));
        d0.setSize(new java.awt.Dimension(50, 50));
        d0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d0ActionPerformed(evt);
            }
        });

        f0.setBackground(new java.awt.Color(255, 255, 255));
        f0.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        f0.setText("O");
        f0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        f0.setPreferredSize(new java.awt.Dimension(50, 50));
        f0.setSize(new java.awt.Dimension(50, 50));
        f0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f0ActionPerformed(evt);
            }
        });

        h0.setBackground(new java.awt.Color(255, 255, 255));
        h0.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        h0.setText("O");
        h0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        h0.setPreferredSize(new java.awt.Dimension(50, 50));
        h0.setSize(new java.awt.Dimension(50, 50));
        h0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h0ActionPerformed(evt);
            }
        });

        a1.setBackground(new java.awt.Color(255, 255, 255));
        a1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        a1.setText("O");
        a1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        a1.setPreferredSize(new java.awt.Dimension(50, 50));
        a1.setSize(new java.awt.Dimension(50, 50));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        c1.setText("O");
        c1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        c1.setPreferredSize(new java.awt.Dimension(50, 50));
        c1.setSize(new java.awt.Dimension(50, 50));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        e1.setBackground(new java.awt.Color(255, 255, 255));
        e1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        e1.setText("O");
        e1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        e1.setPreferredSize(new java.awt.Dimension(50, 50));
        e1.setSize(new java.awt.Dimension(50, 50));
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });

        g1.setBackground(new java.awt.Color(255, 255, 255));
        g1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        g1.setText("O");
        g1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        g1.setPreferredSize(new java.awt.Dimension(50, 50));
        g1.setSize(new java.awt.Dimension(50, 50));
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        b2.setText("O");
        b2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        b2.setPreferredSize(new java.awt.Dimension(50, 50));
        b2.setSize(new java.awt.Dimension(50, 50));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        d2.setBackground(new java.awt.Color(255, 255, 255));
        d2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        d2.setText("O");
        d2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        d2.setPreferredSize(new java.awt.Dimension(50, 50));
        d2.setSize(new java.awt.Dimension(50, 50));
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });

        f2.setBackground(new java.awt.Color(255, 255, 255));
        f2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        f2.setText("O");
        f2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        f2.setPreferredSize(new java.awt.Dimension(50, 50));
        f2.setSize(new java.awt.Dimension(50, 50));
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        h2.setBackground(new java.awt.Color(255, 255, 255));
        h2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        h2.setText("O");
        h2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        h2.setPreferredSize(new java.awt.Dimension(50, 50));
        h2.setSize(new java.awt.Dimension(50, 50));
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });

        g3.setBackground(new java.awt.Color(255, 255, 255));
        g3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        g3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        g3.setPreferredSize(new java.awt.Dimension(50, 50));
        g3.setSize(new java.awt.Dimension(50, 50));
        g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g3ActionPerformed(evt);
            }
        });

        e3.setBackground(new java.awt.Color(255, 255, 255));
        e3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        e3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        e3.setPreferredSize(new java.awt.Dimension(50, 50));
        e3.setSize(new java.awt.Dimension(50, 50));
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });

        c3.setBackground(new java.awt.Color(255, 255, 255));
        c3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        c3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        c3.setPreferredSize(new java.awt.Dimension(50, 50));
        c3.setSize(new java.awt.Dimension(50, 50));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        a3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        a3.setPreferredSize(new java.awt.Dimension(50, 50));
        a3.setSize(new java.awt.Dimension(50, 50));
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        b4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        b4.setPreferredSize(new java.awt.Dimension(50, 50));
        b4.setSize(new java.awt.Dimension(50, 50));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        d4.setBackground(new java.awt.Color(255, 255, 255));
        d4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        d4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        d4.setPreferredSize(new java.awt.Dimension(50, 50));
        d4.setSize(new java.awt.Dimension(50, 50));
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });

        f4.setBackground(new java.awt.Color(255, 255, 255));
        f4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        f4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        f4.setPreferredSize(new java.awt.Dimension(50, 50));
        f4.setSize(new java.awt.Dimension(50, 50));
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        h4.setBackground(new java.awt.Color(255, 255, 255));
        h4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        h4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        h4.setPreferredSize(new java.awt.Dimension(50, 50));
        h4.setSize(new java.awt.Dimension(50, 50));
        h4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h4ActionPerformed(evt);
            }
        });

        g5.setBackground(new java.awt.Color(255, 255, 255));
        g5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        g5.setText("X");
        g5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        g5.setPreferredSize(new java.awt.Dimension(50, 50));
        g5.setSize(new java.awt.Dimension(50, 50));
        g5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g5ActionPerformed(evt);
            }
        });

        e5.setBackground(new java.awt.Color(255, 255, 255));
        e5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        e5.setText("X");
        e5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        e5.setPreferredSize(new java.awt.Dimension(50, 50));
        e5.setSize(new java.awt.Dimension(50, 50));
        e5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e5ActionPerformed(evt);
            }
        });

        c5.setBackground(new java.awt.Color(255, 255, 255));
        c5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        c5.setText("X");
        c5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        c5.setPreferredSize(new java.awt.Dimension(50, 50));
        c5.setSize(new java.awt.Dimension(50, 50));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        a5.setBackground(new java.awt.Color(255, 255, 255));
        a5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        a5.setText("X");
        a5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        a5.setPreferredSize(new java.awt.Dimension(50, 50));
        a5.setSize(new java.awt.Dimension(50, 50));
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        b6.setText("X");
        b6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        b6.setPreferredSize(new java.awt.Dimension(50, 50));
        b6.setSize(new java.awt.Dimension(50, 50));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        d6.setBackground(new java.awt.Color(255, 255, 255));
        d6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        d6.setText("X");
        d6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        d6.setPreferredSize(new java.awt.Dimension(50, 50));
        d6.setSize(new java.awt.Dimension(50, 50));
        d6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d6ActionPerformed(evt);
            }
        });

        f6.setBackground(new java.awt.Color(255, 255, 255));
        f6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        f6.setText("X");
        f6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        f6.setPreferredSize(new java.awt.Dimension(50, 50));
        f6.setSize(new java.awt.Dimension(50, 50));
        f6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f6ActionPerformed(evt);
            }
        });

        h6.setBackground(new java.awt.Color(255, 255, 255));
        h6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        h6.setText("X");
        h6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        h6.setPreferredSize(new java.awt.Dimension(50, 50));
        h6.setSize(new java.awt.Dimension(50, 50));
        h6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h6ActionPerformed(evt);
            }
        });

        g7.setBackground(new java.awt.Color(255, 255, 255));
        g7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        g7.setText("X");
        g7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        g7.setPreferredSize(new java.awt.Dimension(50, 50));
        g7.setSize(new java.awt.Dimension(50, 50));
        g7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g7ActionPerformed(evt);
            }
        });

        e7.setBackground(new java.awt.Color(255, 255, 255));
        e7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        e7.setText("X");
        e7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        e7.setPreferredSize(new java.awt.Dimension(50, 50));
        e7.setSize(new java.awt.Dimension(50, 50));
        e7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e7ActionPerformed(evt);
            }
        });

        c7.setBackground(new java.awt.Color(255, 255, 255));
        c7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        c7.setText("X");
        c7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        c7.setPreferredSize(new java.awt.Dimension(50, 50));
        c7.setSize(new java.awt.Dimension(50, 50));
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        a7.setBackground(new java.awt.Color(255, 255, 255));
        a7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        a7.setText("X");
        a7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        a7.setPreferredSize(new java.awt.Dimension(50, 50));
        a7.setSize(new java.awt.Dimension(50, 50));
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoardLayout = new javax.swing.GroupLayout(Board);
        Board.setLayout(BoardLayout);
        BoardLayout.setHorizontalGroup(
            BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoardLayout.createSequentialGroup()
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BoardLayout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 56, Short.MAX_VALUE))
                            .addGroup(BoardLayout.createSequentialGroup()
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(d0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(f0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoardLayout.createSequentialGroup()
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGap(56, 56, 56)
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoardLayout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGap(56, 56, 56)
                                .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoardLayout.createSequentialGroup()
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGap(56, 56, 56)
                                .addComponent(d6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BoardLayout.createSequentialGroup()
                        .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BoardLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoardLayout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoardLayout.createSequentialGroup()
                                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoardLayout.createSequentialGroup()
                                .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(e5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoardLayout.createSequentialGroup()
                                .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(e7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BoardLayout.setVerticalGroup(
            BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(h0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(f0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel34.setBackground(new java.awt.Color(255, 153, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Select The Piece you want to move then select where you want to move it.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton34.setText("Exit");

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jButton34)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Board, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        
boolean check = true;
int r = 0;
int c = 0;
int ir = 0;
int ic = 0;
String label = "";
String hold1 = "";
String hold2 = "";

// setPieces();

Board orgBoard = new Board();

public void setPieces(){
    
   
    b0.setText(orgBoard.brd[0][1]);
    b2.setText(orgBoard.brd[2][1]);
    b4.setText(orgBoard.brd[4][1]);
    b6.setText(orgBoard.brd[6][1]);
    
    a1.setText(orgBoard.brd[1][0]);
    a3.setText(orgBoard.brd[3][0]);
    a5.setText(orgBoard.brd[5][0]);
    a7.setText(orgBoard.brd[7][0]);
    
    d0.setText(orgBoard.brd[0][3]);
    d2.setText(orgBoard.brd[2][3]);
    d4.setText(orgBoard.brd[4][3]);
    d6.setText(orgBoard.brd[6][3]);
    
    c1.setText(orgBoard.brd[1][2]);
    c3.setText(orgBoard.brd[3][2]);
    c5.setText(orgBoard.brd[5][2]);
    c7.setText(orgBoard.brd[7][2]);
    
    f0.setText(orgBoard.brd[0][5]);
    f2.setText(orgBoard.brd[2][5]);
    f4.setText(orgBoard.brd[4][5]);
    f6.setText(orgBoard.brd[6][5]);
    
    e1.setText(orgBoard.brd[1][4]);
    e3.setText(orgBoard.brd[3][4]);
    e5.setText(orgBoard.brd[5][4]);
    e7.setText(orgBoard.brd[7][4]);
    
    h0.setText(orgBoard.brd[0][7]);
    h2.setText(orgBoard.brd[2][7]);
    h4.setText(orgBoard.brd[4][7]);
    h6.setText(orgBoard.brd[6][7]);
    
    g1.setText(orgBoard.brd[1][6]);
    g3.setText(orgBoard.brd[3][6]);
    g5.setText(orgBoard.brd[5][6]);
    g7.setText(orgBoard.brd[7][6]);
}


    private void g7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int g7r = 7;
       final int g7c = 8;
       label = "g7";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = g7r;
           c = g7c;
           check = false;
       }
       if(!check){
	   ir = g7r;
	   ic = g7c;
    try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
       // g7.setText("F");
       // select.display();
    }                                  

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int a5r = 5;
       final int a5c = 1;
       label = "a5";
       SelectGui select = new SelectGui(); 
       if(check){
	   r = a5r;
           c = a5c;
           check = false;
       }
       else if(!check){
	   ir = a5r;
           ic = a5c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
	   
       }
       // select.display2();
       
    }                                  

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       
	final int b0r = 0;
       final int b0c = 0;
       label = "b0";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = b0r;
           c = b0c;
           check = false;
       }
       else if(!check){
	   ir = b0r;
           ic = b0c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void d0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int d0r = 0;
       final int d0c = 2;
       label = "d0";
       SelectGui select = new SelectGui(); 
      
       if(check){
	   r = d0r;
           c = d0c;
           check = false;
       }
       else if(!check){
	   ir = d0r;
           ic = d0c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void f0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int f0r = 0;
       final int f0c = 4;
       label = "f0";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = f0r;
           c = f0c;
           check = false;
       }
       else if(!check){
	  ir = f0r;
          ic = f0c;
	  try {
	  select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void h0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int h0r = 0;
       final int h0c = 6;
       label = "h0";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = h0r;
           c = h0c;
           check = false;
       }
       else if(!check){
	  ir = h0r;
          ic = h0c;
	   check = true;
       }
    }                                  

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int a1r = 1;
       final int a1c = 1;
       label = "b1";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = a1r;
           c = a1c;
           check = false;
       }
       else if(!check){
	  ir = a1r;
          ic = a1c;
	  try {
	  select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int c1r = 1;
       final int c1c = 3;
       label = "c1";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = c1r;
           c = c1c;
           check = false;
       }
       else if(!check){
	   ir = c1r;
           ic = c1c;
	   try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int e1r = 1;
       final int e1c = 5;
       label = "e1";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = e1r;
           c = e1c;
           check = false;
       }
       else if(!check){
	   ir = e1r;
           ic = e1c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int g1r = 1;
       final int g1c = 7;
       label = "g1";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = g1r;
           c = g1c;
           check = false;
       }
       else if(!check){
	   ir = g1r;
           ic = g1c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int b2r = 2;
       final int b2c = 0;
       label = "b2";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = b2r;
           c = b2c;
           check = false;
       }
       else if(!check){
	   ir = b2r;
           ic = b2c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int d2r = 2;
       final int d2c = 2;
       label = "d2";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = d2r;
           c = d2c;
           check = false;
       }
       else if(!check){
	   ir = d2r;
           ic = d2c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int f2r = 2;
       final int f2c = 4;
       label = "f2";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = f2r;
           c = f2c;
           check = false;
       }
       else if(!check){
	   ir = f2r;
           ic = f2c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int h2r = 2;
       final int h2c = 6;
       label = "h2";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = h2r;
           c = h2c;
           check = false;
       }
       else if(!check){
	   ir = h2r;
           ic = h2c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int a3r = 3;
       final int a3c = 1;
       label = "a3";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = a3r;
           c = a3c;
           check = false;
       }
       else if(!check){
	   ir = a3r;
           ic = a3c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int c3r = 3;
       final int c3c = 3;
       label = "c3";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = c3r;
           c = c3c;
           check = false;
       }
       else if(!check){
	   ir = c3r;
           ic = c3c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int e3r = 3;
       final int e3c = 5;
       label = "e3";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = e3r;
           c = e3c;
           check = false;
       }
       else if(!check){
	   ir = e3r;
           ic = e3c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void g3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int g3r = 3;
       final int g3c = 7;
       label = "g3";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = g3r;
           c = g3c;
           check = false;
       }
       else if(!check){
	   ir = g3r;
           ic = g3c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int b4r = 4;
       final int b4c = 0;
       label = "b4";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = b4r;
           c = b4c;
           check = false;
       }
       else if(!check){
	   ir = b4r;
           ic = b4c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int d4r = 4;
       final int d4c = 2;
       label = "d4";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = d4r;
           c = d4c;
           check = false;
       }
       else if(!check){
	   ir = d4r;
           ic = d4c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int f4r = 4;
       final int f4c = 4;
       label = "f4";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = f4r;
           c = f4c;
           check = false;
       }
       else if(!check){
	   ir = f4r;
           ic = f4c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void h4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int h4r = 4;
       final int h4c = 6;
       label = "h4";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = h4r;
           c = h4c;
           check = false;
       }
       else if(!check){
	   ir = h4r;
           ic = h4c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int c5r = 5;
       final int c5c = 3;
       label = "c5";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = c5r;
	   c = c5c;
           check = false;
       }
       else if(!check){
	   ir = c5r;
	   ic = c5c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void e5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int e5r = 5;
       final int e5c = 5;
       label = "e5";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = e5r;
           c = e5c;
           check = false;
       }
       else if(!check){
	   ir = e5r;
           ic = e5c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void g5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int g5r = 5;
       final int g5c = 7;
       label = "g5";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = g5r;
           c = g5c;
           check = false;
       }
       else if(!check){
	   ir = g5r;
           ic = g5c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int b6r = 6;
       final int b6c = 0;
       label = "b6";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = b6r;
           c = b6c;
           check = false;
       }
       else if(!check){
	   ir = b6r;
           ic = b6c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void d6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int d6r = 6;
       final int d6c = 2;
       label = "d6";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = d6r;
           c = d6c;
           check = false;
       }
       else if(!check){
	   ir = d6r;
           ic = d6c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void f6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int f6r = 6;
       final int f6c = 4;
       label = "f6";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = f6r;
           c = f6c;
           check = false;
       }
       else if(!check){
	   ir = f6r;
           ic = f6c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void h6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int h6r = 6;
       final int h6c = 6;
       label = "h6";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = h6r;
           c = h6c;
           check = false;
       }
       else if(!check){
	   ir = h6r;
           ic = h6c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int a7r = 7;
       final int a7c = 1;
       label = "a7";
       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = a7r;
           c = a7c;
           check = false;
       }
       else if(!check){
	   ir = a7r;
           ic = a7c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int c7r = 7;
       final int c7c = 3;
       label = "c7";

       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = c7r;
           c = c7c;
           check = false;
       }
       else if(!check){
	   ir = c7r;
           ic = c7c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    private void e7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       final int e7r = 7;
       final int e7c = 5;
       label = "e7";

       SelectGui select = new SelectGui(); 
       
       if(check){
	   r = e7r;
           c = e7c;
           check = false;
       }
       else if(!check){
	   ir = e7r;
           ic = e7c;
       try {
	   select.run(r,c,ir,ic);
    } catch (IntelException ex) { 
	Logger.getLogger(BoardGui.class.getName()).log(Level.SEVERE, null, ex);
    }
	   check = true;
       }
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new BoardGui().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Board;
    private javax.swing.JButton a1;
    private javax.swing.JButton a3;
    private javax.swing.JButton a5;
    private javax.swing.JButton a7;
    private javax.swing.JButton b0;
    private javax.swing.JButton b2;
    private javax.swing.JButton b4;
    private javax.swing.JButton b6;
    private javax.swing.JButton c1;
    private javax.swing.JButton c3;
    private javax.swing.JButton c5;
    private javax.swing.JButton c7;
    private javax.swing.JButton d0;
    private javax.swing.JButton d2;
    private javax.swing.JButton d4;
    private javax.swing.JButton d6;
    private javax.swing.JButton e1;
    private javax.swing.JButton e3;
    private javax.swing.JButton e5;
    private javax.swing.JButton e7;
    private javax.swing.JButton f0;
    private javax.swing.JButton f2;
    private javax.swing.JButton f4;
    private javax.swing.JButton f6;
    private javax.swing.JButton g1;
    private javax.swing.JButton g3;
    private javax.swing.JButton g5;
    private javax.swing.JButton g7;
    private javax.swing.JButton h0;
    private javax.swing.JButton h2;
    private javax.swing.JButton h4;
    private javax.swing.JButton h6;
    private javax.swing.JButton jButton34;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
